# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               LAWRENCE BARRINER II
# tagline:             'personal website'
description:         '"everything changes, everything is connected, pay attention." — jane hirschfield'
url:                 http://lqb2.github.io
baseurl:             ''
paginate:            5
plugins:             [jekyll-paginate]
paginate_path:       "page:num"


# About/contact
author:
  name:              Lawrence Barriner II
  url:               https://twitter.com/lqb2
  email:             lawrence.barriner.ii@gmail.com

# Custom vars
version:             1.0.2
